name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: ls -l
      - run: docker build -t sym:test .
      - run: echo "image builded"
      - run: docker run -it -d --name symfonycontainer sym:test
      - run: echo "container runned"
      - run: docker exec symfonycontainer ./bin/phpunit
      - run: echo "unit test executed perfectly"
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t symfony .
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
