name: GitHub Action Symfony demo
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: ls -l
      - run: docker build -t sym:test .
      - run: echo "image builded"
      - run: docker run -it -d --name symfonycontainer sym:test
      - run: echo "container runned"
      - run: docker exec symfonycontainer ./bin/phpunit
      - run: echo "unit test executed perfectly"

  push_container:
    needs: Unit-test
    runs-on: ubuntu-latest
    steps:
      - name: cloning the symfony project
        uses: actions/checkout@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/nourimohammed/githubactionstest:${{ github.sha }}

      - name: display builded images
        run: docker images 

  deploy_in_Azure_webapp:
    needs: push_container
    runs-on: ubuntu-latest
    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.USER_SPN }}","clientSecret":"${{ secrets.AZURE_WEBAPP_SPN }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID_SPN }}"}'
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webapp-actions'
          images: 'ghcr.io/nourimohammed/githubactionstest:${{ github.sha }}'
